name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Run Selenium Tests in Headless Mode
        run: |
          mvn clean test -Dwebdriver.chrome.driver=WebDriverManager \
            -Dwebdriver.chrome.args="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 --user-data-dir=/tmp/selenium-profile-$(uuidgen)"
